services:
  app:
    build: .
    container_name: list-generate
    ports: 
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  db:
    image: mysql:latest
    container_name: db-list-generate
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lg*root
      MYSQL_DATABASE: list-generate
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql

volumes:
  db_data: